language: node_js
sudo: required

services:
  - docker

before_script:
- python -m SimpleHTTPServer 8009 &
- sleep 3

script:
- docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:19.5.0 https://www.bancodelsol.com/
- kill `ps aux | grep "python -m SimpleHTTPServer" | grep -v grep | awk '{print $2}'`
